version: '3'
services:
  picshare:
    build: .
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: pic_share_db
    ports:
      - '5432:5432'
