version: '3'
services:
  picshare:
    build: .
    ports:
      - '3002:3002'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_USER_PWD: 5432
      DB_NAME: pic_share_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: pic_share_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
